name: Enviar Ofertas Coronel
on:
  schedule:
    - cron: '*/30 * * * *' # Roda a cada 30 min
  workflow_dispatch: # Permite rodar na mão para testar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-node: '20'
      - run: npm install axios
      - name: Rodar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ML_TOKEN: ${{ secrets.ML_TOKEN }}
        run: node index.js
