- name: Rodar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ML_ACCESS_TOKEN: ${{ secrets.ML_ACCESS_TOKEN }}
          ML_CLIENT_ID: ${{ secrets.ML_CLIENT_ID }}
          ML_CLIENT_SECRET: ${{ secrets.ML_CLIENT_SECRET }}
          ML_REFRESH_TOKEN: ${{ secrets.ML_REFRESH_TOKEN }}
        run: node index.js
